import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "../app/components/provider/UserProvider";
import { CategoryContext, CategoryProvider } from "./components/provider/CategoryProvider";
import { OrderSidebarProvider } from "./components/provider/OrderSideBar";
import { CartProvider } from "./components/provider/CartProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <CategoryProvider>
            <OrderSidebarProvider>
              <CartProvider>
                {children}
              </CartProvider>
            </OrderSidebarProvider>
          </CategoryProvider>
        </UserProvider>
      </body>
    </html >
  );
}
